### PR TITLE
do not use `mem::replace`

### PR DESCRIPTION
**Pull request by ariesdevil**
I separate `format code` to an extra commit so you can review it easily.

### CODE REVIEW

**Comment by Flakebi** [comment]
I think following rustc’s suggestion and doing `**tab = [0u32; HASHTABLE_SIZE];` instead of `mem::replace` is better and seems to work too. I have no idea why I used `mem::replace` there.

**Comment by ariesdevil** [comment]
fixed: https://github.com/ReSpeak/quicklz/pull/4/commits/59ba55c90c5d0c8f7a239762bc9430be49685660

**Comment by Flakebi** [comment]
Thanks!

**Comment by ariesdevil** [comment]
You taught me not to use `mem::replace` this in this situation, thank you too.

**Pull request merged**
